#!/bin/sh

PKG_NAME=
PKG_VERSION=
LINK=
BINARY="$PKG_NAME"
OUTPUT_DIR="$PWD/../_output"
CWD="$(pwd)"

TMPDIR="$(mktemp -d)"
cd "$TMPDIR" || exit 1

[ "$1" != "" ] && PKG_VERSION="$1"

set -e

# apk add glib-static

wget -O ${PKG_NAME}-${PKG_VERSION}.tar.xz -c $LINK
tar xvf ${PKG_NAME}-${PKG_VERSION}.tar.xz

cd ${PKG_NAME}*${PKG_VERSION}*/

./configure CFLAGS="-static -Os" LDFLAGS="-static"
make -j"$(expr "$(nproc)" + 1)"

strip src/$BINARY
mkdir -p "$OUTPUT_DIR"
mv -v src/$BINARY "$OUTPUT_DIR/$BINARY"

cd "$CWD"
rm -rf "$TMPDIR"

echo "Binário salvo em $OUTPUT_DIR/$BINARY"
