#!/bin/sh

PKG_NAME=cmatrix
BINARY="$PKG_NAME"
PKG_VERSION='2.0'
OUTPUT_DIR="$PWD/_output"
CWD="$(pwd)"

TMPDIR="$(mktemp -d)"
cd "$TMPDIR" || exit 1

[ "$1" != "" ] && PKG_VERSION="$1"

set -e

apk add ncurses-dev kbd autoconf automake ncurses-static

wget -O ${PKG_NAME}-${PKG_VERSION}.tar.xz -c https://github.com/abishekvashok/cmatrix/archive/v$PKG_VERSION.tar.gz
tar xvf ${PKG_NAME}-${PKG_VERSION}.tar.xz

cd ${PKG_NAME}*${PKG_VERSION}*/

autoreconf -i
./configure CFLAGS="-static -Os" LDFLAGS="-static"
make -j"$(expr "$(nproc)" + 1)"

strip ./$BINARY
mkdir -p "$OUTPUT_DIR"
mv -v ./$BINARY "$OUTPUT_DIR/$BINARY"

cd "$CWD"
rm -rf "$TMPDIR"

echo "Binário salvo em $OUTPUT_DIR/BINARY"
