#!/bin/sh

PKG_NAME=lynx
BINARY="$PKG_NAME"
PKG_VERSION='2.9.2'
OUTPUT_DIR="$PWD/_output"
CWD="$(pwd)"

TMPDIR="$(mktemp -d)"
cd "$TMPDIR" || exit 1

[ "$1" != "" ] && PKG_VERSION="$1"

set -e

apk add openssl-dev gettext zlib-dev glib-dev perl ncurses-dev openssl-libs-static zlib-static ncurses-static glib-static

wget -O ${PKG_NAME}-${PKG_VERSION}.tar.xz -c https://invisible-mirror.net/archives/lynx/tarballs/lynx$PKG_VERSION.tar.bz2
tar xvf ${PKG_NAME}-${PKG_VERSION}.tar.xz

cd ${PKG_NAME}*${PKG_VERSION}*/

./configure CFLAGS="-static -Os" LDFLAGS="-static" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-ipv6 \
    --with-ssl \
    --enable-default-colors \
    --with-screen=ncursesw \
    --with-zlib \
    --disable-full-paths \
    --enable-externs \
    --enable-nls
make -j"$(expr "$(nproc)" + 1)"

strip src/$BINARY
mkdir -p "$OUTPUT_DIR"
mv -v src/$BINARY "$OUTPUT_DIR/$BINARY"

cd "$CWD"
rm -rf "$TMPDIR"

echo "Binário salvo em $OUTPUT_DIR/$BINARY"
