#!/bin/sh

PKG_NAME=fzf
PKG_VERSION=0.63.0
LINK=https://github.com/junegunn/fzf/archive/v$PKG_VERSION.tar.gz
BINARY="$PKG_NAME"
OUTPUT_DIR="$PWD/../_output"
CWD="$(pwd)"

TMPDIR="$(mktemp -d)"
cd "$TMPDIR" || exit 1

[ "$1" != "" ] && PKG_VERSION="$1"

set -e

apk add go

wget -O ${PKG_NAME}-${PKG_VERSION}.tar.gz -c $LINK
tar xvf ${PKG_NAME}-${PKG_VERSION}.tar.gz

cd ${PKG_NAME}*${PKG_VERSION}*/
SRC_DIR="$(pwd)"

export GOROOT="$HOME/.ALPack/usr/lib/go"
export GOTOOLDIR="$HOME/.ALPack/usr/lib/go/pkg/tool/linux_amd64/"

CGO_ENABLED=1 \
go build -a -ldflags="-linkmode external -extldflags '-static' -s -w -X main.version=$PKG_VERSION"

strip $BINARY
mkdir -p "$OUTPUT_DIR"
mv -v $BINARY "$OUTPUT_DIR/$BINARY"

cd "$CWD"
rm -rf "$TMPDIR"

echo "Binário salvo em $OUTPUT_DIR/$BINARY"
